ALTER TYPE "VehicleType" ADD VALUE IF NOT EXISTS 'FLATBED_OPEN';
ALTER TYPE "VehicleType" ADD VALUE IF NOT EXISTS 'FLATBED_ENCLOSED';
ALTER TYPE "VehicleType" ADD VALUE IF NOT EXISTS 'SMALL_TRUCK';
ALTER TYPE "VehicleType" ADD VALUE IF NOT EXISTS 'MEDIUM_TRUCK';
ALTER TYPE "VehicleType" ADD VALUE IF NOT EXISTS 'PICKUP';
ALTER TYPE "VehicleType" ADD VALUE IF NOT EXISTS 'MOTORCYCLE';

CREATE TYPE "DriverVehicleCondition" AS ENUM (
  'EXCELLENT',
  'GOOD',
  'NEEDS_MAINTENANCE'
);

CREATE TYPE "DriverVehicleReviewStatus" AS ENUM (
  'PENDING_REVIEW',
  'APPROVED',
  'REJECTED',
  'INACTIVE'
);

ALTER TYPE "DriverDocumentType" ADD VALUE IF NOT EXISTS 'VEHICLE_FRONT_PHOTO';
ALTER TYPE "DriverDocumentType" ADD VALUE IF NOT EXISTS 'VEHICLE_REAR_PHOTO';
ALTER TYPE "DriverDocumentType" ADD VALUE IF NOT EXISTS 'VEHICLE_SIDE_PHOTO';
ALTER TYPE "DriverDocumentType" ADD VALUE IF NOT EXISTS 'VEHICLE_LICENSE_PLATE_PHOTO';
ALTER TYPE "DriverDocumentType" ADD VALUE IF NOT EXISTS 'VEHICLE_REGISTRATION_FRONT';
ALTER TYPE "DriverDocumentType" ADD VALUE IF NOT EXISTS 'VEHICLE_REGISTRATION_BACK';
ALTER TYPE "DriverDocumentType" ADD VALUE IF NOT EXISTS 'VEHICLE_INSURANCE_DOCUMENT';

ALTER TABLE "driver_vehicles"
ADD COLUMN "condition" "DriverVehicleCondition" NOT NULL DEFAULT 'GOOD',
ADD COLUMN "insuranceExpiryDate" TIMESTAMP(3),
ADD COLUMN "registrationExpiryDate" TIMESTAMP(3),
ADD COLUMN "status" "DriverVehicleReviewStatus" NOT NULL DEFAULT 'APPROVED',
ADD COLUMN "rejectionReason" TEXT;

CREATE INDEX "driver_vehicles_status_idx" ON "driver_vehicles"("status");
