ALTER TYPE "DriverDocumentType" ADD VALUE IF NOT EXISTS 'PERSONAL_SELFIE';
ALTER TYPE "DriverDocumentType" ADD VALUE IF NOT EXISTS 'ID_FRONT';
ALTER TYPE "DriverDocumentType" ADD VALUE IF NOT EXISTS 'ID_BACK';
ALTER TYPE "DriverDocumentType" ADD VALUE IF NOT EXISTS 'DRIVING_LICENSE';
ALTER TYPE "DriverDocumentType" ADD VALUE IF NOT EXISTS 'SELF_IDENTITY_VERIFICATION';

ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'UPLOADED';
ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'UNDER_REVIEW';

ALTER TABLE "driver_profiles"
ADD COLUMN "submittedForReviewAt" TIMESTAMP(3);

ALTER TABLE "driver_documents"
ADD COLUMN "reviewedAt" TIMESTAMP(3);
